on:
  pull_request_review:
    types: [submitted]
    branches: ['main','dev']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}

      - name: Pull Request URL
        uses: kceb/pull-request-url-action@v2
        id: pr-url

      - name: pr info
        run: echo "${{ steps.pr-url.outputs.url }}"